DROP SCHEMA IF EXISTS Money;
Create Schema Money;
USE Money;
CREATE TABLE Users (
	UID INT AUTO_INCREMENT PRIMARY KEY,
    UName VARCHAR(255) NOT NULL, 
    UPassword VARCHAR(255),
    UAccount VARCHAR(255),
    UNickname VARCHAR(255),
    NoticeTime TIME
    isrightHander BOOLEAN
    isDarkMode BOOLEAN
    Budget int 
);

CREATE TABLE Ledgers (
    LID INT AUTO_INCREMENT PRIMARY KEY,
    LName VARCHAR(255) DEFAULT NULL,
    UID INT,
    FOREIGN KEY (UID) REFERENCES Users(UID)
);

CREATE TABLE Datas (
	DID INT AUTO_INCREMENT PRIMARY KEY,
    DName VARCHAR(255) NOT NULL,
    Price INT,
    DType VARCHAR(255),
    DDate DATE,
    LID INT,
    UID INT,
    FOREIGN KEY (LID) REFERENCES Ledgers(LID),
    FOREIGN KEY (UID) REFERENCES Users(UID)
);