DROP DATABASE IF EXISTS JiDB;
CREATE DATABASE JiDB;
USE JiDB;
CREATE TABLE Users(
	UID INT NOT NULL AUTO_INCREMENT,
    BUDGET INT NOT NULL DEFAULT 0,
    UName VARCHAR(255) NOT NULL,
    UPassword VARCHAR(255) NOT NULL,
    UAccount VARCHAR(255) NOT NULL,
    UNickname VARCHAR(255) NOT NULL,
    isrightHander BOOLEAN NOT NULL DEFAULT TRUE,
    isDarkMode BOOLEAN NOT NULL DEFAULT FALSE,
    NoticeTime DATE NOT NULL,
    PRIMARY KEY (UID)
);

CREATE TABLE Ledgers(
	LID INT AUTO_INCREMENT NOT NULL,
    UID INT NOT NULL,
    LName VARCHAR(16) NOT NULL,
    PRIMARY KEY (LID)
);

CREATE TABLE Datas(
	DID INT AUTO_INCREMENT NOT NULL,
    LID INT NOT NULL,
    UID INT NOT NULL,
    Price INT NOT NULL,
    DName VARCHAR(16) NOT NULL,
    DType VARCHAR(16) NOT NULL,
    DDate DATE NOT NULL,
    PRIMARY KEY (DID)
);

ALTER TABLE Ledgers
ADD CONSTRAINT `fk_Ledgers_to_Users_UID` FOREIGN KEY (UID) REFERENCES Users(UID)ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Datas
ADD CONSTRAINT `fk_Datas_to_Ledgers_UID` FOREIGN KEY (UID) REFERENCES Ledgers(UID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Datas
ADD CONSTRAINT `fk_Datas_to_Ledgers_LID` FOREIGN KEY (LID) REFERENCES Ledgers(LID) ON DELETE CASCADE ON UPDATE CASCADE;